### ISSUE TITLE
Incluir gráfico de habilidades técnicas

### ISSUE THREAD

**Issue by teles** [woliveiras/resume#1]
Incluir um gráfico parecido com esse:
![screen shot 2016-02-03 at 1 36 52 pm](https://cloud.githubusercontent.com/assets/762639/12787154/4ad7f9c0-ca7b-11e5-9314-1a09ed5ad9ba.png)

(Seria melhor ainda se fosse no modelo dos gráficos de PAPI)

**Comment by woliveiras** [comment]
Só quando sair o projeto do PAPI! :stuck_out_tongue:

**Comment by teles** [comment]
Beleza, @woliveiras. Demorará.

**Comment by woliveiras** [comment]
Jay Tels, reabrimos essa issue ao termos o projeto do PAPI em mãos? :stuck_out_tongue:

**Comment by teles** [comment]
@woliveiras pode ser :D
