### ISSUE TITLE
Disponibilizar um formulário para quem quiser escrever um depoimento

### ISSUE THREAD

**Issue by teles** [woliveiras/resume#2]
Esse negócio de ter que ver o modelo para escrever um depoimento é meio enfadonho, amigo.

Sugestão de mvp:

Disponbilizar um formulário feito com [formspree](http://formspree.io/) para pessoa preencher um depoimento para você.

Campos:
- Nome
- Profissão
- Onde trabalhamos juntos/ Onde você me conhece
- Depoimento

Essa é uma versão mvp, legal mesmo seria a pessoa logar com github, preencher o form e o form ser enviado como pull request de depoimento.

**Comment by woliveiras** [comment]
Opre, pensarei numa fita dessas!

**Comment by woliveiras** [comment]
Jay Tels, acho que por conta daquela conversa de testimonies parecer Orkut, podemos fechar essa issue né? kkkk
